### ISSUE TITLE
Posible colaboración

### ISSUE THREAD

**Issue by mmanzano** [sukycms/sukycms#1]
Hola @jaimesares:

El otro día hablando en un foro de gente que programa me planteé si era buena idea hacer algo muy parecido a lo que estás haciendo. Estábamos todavía explorando si había una necesidad por parte de las protectoras. ¿Aceptas colaboraciones?

Estas eran un poco las preguntas que me hacía en voz alta:

- Para la parte pública:

¿Usan las protectoras alguna aplicación para gestionar los gatos/perros que tienen en adopción?

¿Esa aplicación cubre todo lo que necesitan?

¿Qué necesitan?

- Para la parte privada (no visible para todo el mundo, sólo para la protectora):

¿Vendría bien una herramienta para poder gestionar vuestros refugios/casas de acogida?

Acerca de las colonias urbanas. ¿Se controlan de alguna manera por vuestra parte? ¿Sería útil controlarlas de alguna manera? Entiendo que cada territorio es un mundo.

¿Les interesaría tener un listado de veterinarios de confianza?

¿Os interesaría poder cobrar donativos mensuales o donaciones puntuales? Aquí en Murcia también usan teaming para eso así que entiendo que es una necesidad y he visto también alguna campaña para poder esterilizar u operar. Esto entiendo que es un mix entre parte pública (para que la gente pueda hacer donaciones) y privada (para que la protectora pueda cobrarlas).

Saludos.

**Comment by jaimesares** [comment]
Hola @mmanzano,

Actualmente está en marcha y en funcionamiento el proyecto protecms.com. Actualmente lo usan decenas de asociaciones y por lo que me comentan están muy contentas de usarlo y les facilita mucho la gestión.

A la pregunta de si acepto colaboraciones, si. Mi idea es empezar a aceptarla una vez el proyecto se lance (para diciembre), ya que actualmente carezco de poco tiempo y no dispongo de todo lo necesario para poder organizar y gestionar todo lo que tengo en la cabeza y trasladarlo a otros.

Respecto a las preguntas, con protecms.com hay voluntarias que organizan sus colonias, otras asociaciones que sí tienen refugios, otras que solo funcionan con casas de acogida, por lo tanto sí, el proyecto tiene cabida para todas las opciones que planteas y más ya que será modular y se podrán activar y desactivar estos módulos dependiendo de las necesidades de las asociaciones.

También hay gestión de casas de acogida, apadrinamientos, finanzas y más, por lo que con el proyecto se pueden gestionar casi todos los aspectos de una asociación a falta de la posibilidad de crear una tienda online, que sí incluirá sukycms.com. No te voy a negar de que faltan muchos aspectos o detalles que iré completando en sukycms.com.

El proyecto no dispone de aplicaciones para móviles, pero la página web es responsive por lo que es totalmente gestionable usando móviles o tablets, aunque es algo que en un futuro sí me gustaría tener.

Para terminar, en el aspecto económico cada asociación se encarga de tener su teaming, etc... SukyCMS también lo tiene: https://www.teaming.net/sukycms. Mi proyecto no hace lo que otros que permite donar o apadrinar dentro del proyecto y se lleva una comisión por "gestiones". Ni lo hará jamás.

Creo que respondo a todas tus preguntas, si tienes alguna duda, no dudes en comentármelo y estaré encantado de atenderte.

Un saludo!

**Comment by mmanzano** [comment]
Jajaja.... perfecto... pues te he dejado entonces alguna idea por si no lo habías pensado (que supongo que sí). Avisa cuando se pueda colaborar con código en el proyecto. Será un placer y gracias por todo el trabajo que estás haciendo.
